#ifndef __MESSAGE_H__
#define __MESSAGE_H__

enum Message
{
	API_FAIL,
	API_SUCCESS,
	ConnectComPort_ERROR =                                 				0x10,
	ConnectComPort_CREATE_COMPORT_FAIL,
	ConnectComPort_GET_COMPORT_STATE_FAIL,
	ConnectComPort_SET_COMPORT_STATE_FAIL,
	ConnectComPort_OPEN_KEY_FAIL,
	ConnectComPort_SETUP_COMPORT_FAIL,
	ConnectComPort_PURGE_COMPORT_FAIL,
	FILE_NOT_EXIST =                         	   						0x20,
	SEND_PACKAGE_TIME_OUT,
	PACKAGE_CHECKSUM_ERROR,
	READ_DATA_FAIL =                 	   								0x30,
	FILE_CHECKSUM_ERROR =      											0x40,
	ClearFlash_FAIL =                                                   0x50,
	ClearFlashMASA_START_ADDR_ERROR,
	ClearFlashMASA_CLEAR_RANGE_ERROR,
	ConvertBinFile_FAIL = 												0x60,
	ConvertBinFile_CREATE_CSV_FILE_FAIL,
	ConvertBinFile_CREATE_KML_FILE_FAIL,
	ConvertBinFile_CREATE_NMEA_FILE_FAIL,
	AllocateThreadParameter_MEMORY_NULL =                               0x70,
	ConvertCourseFile_FAIL =                                            0x80,
	ConvertCourseFile_TIME_OUT,
	CheckNMEAAck_FAIL =                                                 0x90,
	//PACKAGE_CHECKSUM_ERROR,
	DFU_PACKAGE_FAIL =                                                  0xA0,
	DFU_ACK_FORMAT_ERROR,
	DFU_ACK_CHECKSUM_ERROR,
	DFU_ACK_ACK_NUM_ERROR,
	EXTRA_TEST_FAIL =                                                   0xB0,
	EXTRA_TEST_SN_ERROR,
	EXTRA_TEST_CHECK_VER_ERROR,
	EXTRA_TEST_CHECK_BOOT_VER_ERROR,
	EXTRA_TEST_CHECK_AP_VER_ERROR,
	EXTRA_TEST_CHECK_COURSE_VER_ERROR,
	EXTRA_TEST_CHECK_COURSE_NAME_VER_ERROR,
	EXTRA_TEST_CHECK_WAVE_VER_ERROR,
	EXTRA_TEST_CHECK_BLE_VER_ERROR,
	EXTRA_TEST_CHECK_FLASH_ID_ERROR,
	EXTRA_TEST_WRITE_SN_ERROR,
	FINAL_TEST_FAIL =                                                   0xC0,
	FINAL_TEST_VER_ERROR,
	FINAL_TEST_NMEA_ERROR,
	FINAL_TEST_TTFF_ERROR,
	FINAL_TEST_SNR_ERROR,
	FINAL_TEST_SIGNAL_ERROR,
	FINAL_TEST_ACQ_ERROR,
	FINAL_TEST_BIT_SYNC_ERROR,
	UPDATE_GPS_FAIL =                                                   0xD0,
	UPDATE_GPS_DA_START_CMD_FAIL,
	UPDATE_GPS_DA_FAIL,
    //FINAL_TEST_PASS,
	WINDOWS_ERROR =                                                     0x1000
} ;

enum ShowMessageEvent
{
	CLEAR_MESSAGE_OFFSET,
	NOT_SHOW_WINDOW_OFFSET,
	SHOW_SUCCESS_WINDOW_OFFSET,
	SHOW_ERROR_WINDOW_OFFSET,
	SHOW_SUCCESS_MESSAGE_OFFSET,
	SHOW_ERROR_MESSAGE_OFFSET,
	CLEAR_MESSAGE =                 (1 << CLEAR_MESSAGE_OFFSET),
	NOT_SHOW_WINDOW =               (1 << NOT_SHOW_WINDOW_OFFSET),
	SHOW_SUCCESS_WINDOW = 	   		(1 << SHOW_SUCCESS_WINDOW_OFFSET),
	SHOW_ERROR_WINDOW = 			(1 << SHOW_ERROR_WINDOW_OFFSET),
	SHOW_SUCCESS_MESSAGE =			(1 << SHOW_SUCCESS_MESSAGE_OFFSET),
	SHOW_ERROR_MESSAGE =            (1 << SHOW_ERROR_MESSAGE_OFFSET)
} ;

const unsigned char *mMessageStr[] = {
"API_FAIL", "API_SUCCESS", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0",
"ConnectComPort_ERROR", "ConnectComPort_CREATE_COMPORT_FAIL", "ConnectComPort_GET_COMPORT_STATE_FAIL", "ConnectComPort_SET_COMPORT_STATE_FAIL", "ConnectComPort_OPEN_KEY_FAIL", "ConnectComPort_SETUP_COMPORT_FAIL", "ConnectComPort_PURGE_COMPORT_FAIL", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0",
"FILE_NOT_EXIST", "SEND_PACKAGE_TIME_OUT", "PACKAGE_CHECKSUM_ERROR", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0",
"READ_DATA_FAIL", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0",
"FILE_CHECKSUM_ERROR", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0",
"ClearFlash_FAIL", "ClearFlashMASA_START_ADDR_ERROR", "ClearFlashMASA_CLEAR_RANGE_ERROR", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0",
"ConvertBinFile_FAIL", "ConvertBinFile_CREATE_CSV_FILE_FAIL", "ConvertBinFile_CREATE_KML_FILE_FAIL", "ConvertBinFile_CREATE_NMEA_FILE_FAIL", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0",
"AllocateThreadParameter_MEMORY_NULL", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0",
"ConvertCourseFile_FAIL", "ConvertCourseFile_TIME_OUT", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0",
"CheckNMEAAck_FAIL", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0",
"DFU_PACKAGE_FAIL", "DFU_ACK_FORMAT_ERROR", "DFU_ACK_CHECKSUM_ERROR", "DFU_ACK_ACK_NUM_ERROR", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0", "\0",
"EXTRA_TEST_FAIL", "EXTRA_TEST_SN_ERROR", "EXTRA_TEST_CHECK_VER_ERROR", "EXTRA_TEST_CHECK_BOOT_VER_ERROR", "EXTRA_TEST_CHECK_AP_VER_ERROR", "EXTRA_TEST_CHECK_COURSE_VER_ERROR", "EXTRA_TEST_CHECK_COURSE_NAME_VER_ERROR", "EXTRA_TEST_CHECK_WAVE_VER_ERROR", "EXTRA_TEST_CHECK_BLE_VER_ERROR", "EXTRA_TEST_CHECK_FLASH_ID_ERROR", "EXTRA_TEST_WRITE_SN_ERROR", "\0", "\0", "\0", "\0", "\0", "\0",
"FINAL_TEST_FAIL", "FINAL_TEST_VER_ERROR", "FINAL_TEST_NMEA_ERROR", "FINAL_TEST_TTFF_ERROR", "FINAL_TEST_SNR_ERROR", "FINAL_TEST_SIGNAL_ERROR", "FINAL_TEST_ACQ_ERROR", "FINAL_TEST_BIT_SYNC_ERROR", "\0", "\0", "\0", "\0", "\0", "\0", "\0",
"UPDATE_GPS_FAIL", "UPDATE_GPS_DA_START_CMD_FAIL"} ;

#endif
